---
- hosts: all
  connection: local
  gather_facts: true
  tasks:
  - name: install packages with homebrew
    homebrew:
      name: '{{ item }}'
      state: latest
      update_homebrew: yes
    loop: 
      - '{{ brew_formulas }}'
    tags:
      - homebrew
      - formulas

  - name: install homebrew casks
    homebrew_cask:
      name: "{{ item }}"
      state: present
    loop: "{{ brew_casks }}"
    tags:
      - homebrew
      - casks

# TODO: Copy sift configuration file to ~/.sift/conf

  - name: install global ruby gems
    gem:
      name: '{{ item }}'
      state: present
      user_install: no
    loop: "{{ global_ruby_gems }}"
    become: true  

  - name: install user ruby gems
    gem:
      name: '{{ item }}'
      state: present
      user_install: yes
    loop: "{{ user_ruby_gems }}"

  - name: install pip packages (present, not latest)
    pip: name={{ item }} state=present
    loop: "{{ pip_packages }}"
    become: true

  - name: Install node.js packages globally.
    npm:
      name: '{{ item }}'
      global: yes
    loop: "{{ npm_packages }}"

#  - handlers:
#    - restart SystemUIServer
#      command: killall SystemUIServer
...